# Generated by Django 3.1.4 on 2020-12-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201227_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
    ]
