# Generated by Django 3.1.4 on 2020-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.FileField(default=2, upload_to='article_pic'),
            preserve_default=False,
        ),
    ]
