# Generated by Django 3.1.4 on 2020-12-28 07:08

import blog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=blog.fields.RestrictedFileField(blank=True, null=True, upload_to='article_pic'),
        ),
    ]
